Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/04/2019
Var
// Seção de Declarações das variáveis 
   n : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   n <- 10
   repita
         escreval (n)
         n <- n - 1
   ate n = 0

Fimalgoritmo